[package]
name = "account-match"
version = "0.1.0"
description = "Account Data Matching"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.15.2"
borsh = "0.9.3"


[lib]
crate-type = ["cdylib", "lib"]
name = "account_match"

[features]
no-entrypoint = []